name: dml
channels:
- defaults
- pytorch
dependencies:
- python=3.7
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- h5py
- spacy
- unidecode
- pytorch-cpu
- torchvision-cpu
- pip:
  - future
  - tb-nightly
  - gym
  - pillow
